- name: Create Azure Kubernetes Service using Ansible
  hosts: localhost
  connection: local
  vars:
    resource_group: Kubernetes-US
    location: eastus
    aks_name: AKS-Cluster
    username: azure
    ssh_key: SHA256:K9B7FHgmpB3NFAC0OF7jJbjfII7cxNC0AYjUzeuu5vc ansible@Ansible-VM
    client_id: "{{Azure_client_id}}"
    client_secret: "{{Azure_client_secret}}"
    aks_version: 1.23.5
  tasks:
  - name: Create a managed Azure Container Services (AKS) cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      kubernetes_version: "{{aks_version}}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      max_pods: 5
      agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_D2_v2
      tags:
        Environment: Testing